<a href="https://colab.research.google.com/github/kjaid0341-creator/DATA-SCIENCE--1/blob/main/lec4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
# create array
import numpy as np
a=np.array([1,2,3,4,"2"])#it only takes one type of data type is there is on e string in the integer string it will make whole element a string
print(a)

['1' '2' '3' '4' '2']


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,'hello',False])
# all the data will beconverted into array  therefore false becomes an  string and bool take it as true cause it takes 0,False as false
print(bool(a[-1]))
l="nnnnrjnjnjn";
print(bool(l))

x=False
print(bool(x))



True
True
False


In [ ]:
import numpy as np
a=np.zeros(3)# gives array whose all elment are zero
print(a)
# 2d array
a=np.zeros((2,3))
print(a)
## 3d array
a=np.zeros((3,3,3))
print(a)
print(type(a[1][1][1]))#inside element is numpy.float64
#to change the data type
a=np.zeros(3,dtype=int);
b=np.ones(3,dtype=int);
print(a)
print(b)


[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.float64'>
[0 0 0]
[1 1 1]


In [ ]:
import numpy as np
a=np.empty(3)#it gives garbage value as a data
# to give data according to us
b=np.full(3,5,dtype=str)
print(b)

c=np.arange(1,6,1,dtype=int)#start,stop,step
print(c)
d=np.linspace(1,6,4,dtype=int)#(start,stop,how many parts the no should be devide in between the range)
print(d)

['5' '5' '5']
[1 2 3 4 5]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.ones((3,4))
print(a)
print(a.shape)
print(a.size)#total number of elements
print(a.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
12
float64


In [ ]:
#broadcasting
import numpy as np
a=np.arange(1,10,1,dtype=int)
print(a)
b=np.random.randint(1,7,6)#create a array which have random element in a given range((start,stop),size of a array)
c=np.random.randint(2,7,6)
print(np.random.choice(a))#choise from a particular givn array random number

[1 2 3 4 5 6 7 8 9]
4


In [ ]:
import numpy as np
b=np.random.randint(1,7,6)#create a array which have random element in a given range((start,stop),size of a array)
c=np.random.randint(2,7,6)
print(b,c)
print(b*2*c)
print(b+c)
print(b-c)
print(b/c)#operation performs in corrosponding elements

d=np.ones((2,3),dtype=int)
e=np.zeros((2,3),dtype=int)
print(d+e)

[4 5 3 1 6 6] [2 4 6 5 3 3]
[16 40 36 10 36 36]
[6 9 9 6 9 9]
[ 2  1 -3 -4  3  3]
[2.   1.25 0.5  0.2  2.   2.  ]
[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
a = np.random.randint(2, 7, 6)
b = np.random.randint(2, 7, 6)
print(a)
x = a.reshape(2, 3)
y = a.reshape(2, 3)
print(x)
print(x.transpose())
print(".  ")
print(np.concatenate((x, y),axis=1))
print(np.concatenate((a, b),axis=0))

[3 4 6 6 2 5]
[[3 4 6]
 [6 2 5]]
[[3 6]
 [4 2]
 [6 5]]
.  
[[3 4 6 3 4 6]
 [6 2 5 6 2 5]]
[3 4 6 6 2 5 5 5 3 6 2 6]


In [ ]:
import numpy as np
a = np.random.randint(2, 7, 6)
b = np.random.randint(2, 7, 6)
print(a,b)
c=np.where(b>2,b,a)#check each element indivadulally on corrosponding elements
print(c)
c=np.sort(a)
print(c)
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.unique(a))#give list of unique element
print(np.min(a))
print(np.std(a))
print(np.matmul(a,b))#matrix multiplication
print(np.random.choice(a))#give random nuber on the give list


[2 6 3 3 5 4] [5 4 6 3 6 6]
[5 4 6 3 6 6]
[2 3 3 4 5 6]
23
3.8333333333333335
6
[2 3 4 5 6]
2
1.3437096247164249
115
2


In [ ]:
import numpy as np
a=input("enter").split()
ar=np.array(a,dtype=int)
print(ar)
val=np.sum(ar)
print("sum :",val)
val=np.mean(ar)
i = np.where(ar == val)
print("mean :",val, "on:",i[0]+1)
val=np.max(ar)
i = np.where(ar == val)
print("max :",np.max(ar),"on:",i[0]+1)
print("unique. score :",np.unique(ar))#give list of unique element
val=np.min(ar)
i = np.where(ar == val)
print("min :",val,"on:",i[0]+1)
print("std :",np.std(ar))
print("random score :",np.random.choice(ar))




enter1 2 3 4 5 67 7
[ 1  2  3  4  5 67  7]
sum : 89
mean : 12.714285714285714 on: []
max : 67 on: [6]
unique. score : [ 1  2  3  4  5  7 67]
min : 1 on: [1]
std : 22.237126521166516
random score : 7


In [ ]:
import numpy as np

days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']  # Standard capitalization
scores = []

for i in range(7):
    # Use f-string with curly braces {}
    x = int(input(f"Enter the score for {days[i]} day: "))
    scores.append(x)

# Convert to NumPy array if needed
scores_array = np.array(scores)
print(scores_array)

SyntaxError: invalid syntax (885149881.py, line 4)

In [ ]:
# question HOMEWORK for making products