<a href="https://colab.research.google.com/github/kjaid0341-creator/DATA-SCIENCE--1/blob/main/lec5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
items = []
prices = []

for i in range(7):
    name = input(f"Enter name of item {i+1}: ")
    price = float(input(f"Enter price of {name}: "))

    items.append(name)
    prices.append(price)

prices = np.array(prices)


max_price = np.max(prices)
min_price = np.min(prices)
mean_price = np.mean(prices)
std_price = np.std(prices)


max_item = items[np.argmax(prices)]#return max value index number
min_item = items[np.argmin(prices)]#return min value index number

print("\n----- Results -----")
print(f"Most expensive item : {max_item} (₹{max_price})")
print(f"Cheapest item       : {min_item} (₹{min_price})")
print(f"Average price       : ₹{mean_price:.2f}")
print(f"Standard Deviation  : ₹{std_price:.2f}")

Enter name of item 1: seed
Enter price of seed: 20.2
Enter name of item 2: dal
Enter price of dal: 40
Enter name of item 3: Glucond
Enter price of Glucond: 20
Enter name of item 4: milk
Enter price of milk: 80
Enter name of item 5: suger
Enter price of suger: 90
Enter name of item 6: namak
Enter price of namak: 20
Enter name of item 7: aloooo
Enter price of aloooo: 1000

----- Results -----
Most expensive item : aloooo (₹1000.0)
Cheapest item       : Glucond (₹20.0)
Average price       : ₹181.46
Standard Deviation  : ₹335.27


In [ ]:
import numpy as np
a=np.random.randint(1,90,25,dtype=int)
x=a.reshape(5,5)
print(x)
for i in range(5):
  print(f"mean of row {i+1} is {np.mean(x[i])}")# or print(np.mean(x,axis=1))
# mean of coloumn wise
print(np.mean(x,axis=0))
# for i in range(5):
#     for r in range(5):
#         if (x[i][r]%2==0):
#             x[i][r]=-1
# print(x)
#or
l=np.where(x%2==0,-1,x);
print(l)
sorow=np.sort(x,axis=1)#coloumn wise sort
print(sorow)
sorcol=np.sort(x,axis=0)#row wise sort
print(sorcol)
srow=np.sum(x,axis=1)
print(srow)
scol=np.sum(x,axis=0)
print(scol)
# for counting number of negitives in each coloumn

cnt=np.where(l<0,1,0)

print(np.sum(cnt,axis=0))


[[12 80 74  4 44]
 [56 17 60 24 36]
 [40  2 23 56 65]
 [77 62 61 14 27]
 [86 21 78 56 29]]
mean of row 1 is 42.8
mean of row 2 is 38.6
mean of row 3 is 37.2
mean of row 4 is 48.2
mean of row 5 is 54.0
[54.2 36.4 59.2 30.8 40.2]
[[-1 -1 -1 -1 -1]
 [-1 17 -1 -1 -1]
 [-1 -1 23 -1 65]
 [77 -1 61 -1 27]
 [-1 21 -1 -1 29]]
[[ 4 12 44 74 80]
 [17 24 36 56 60]
 [ 2 23 40 56 65]
 [14 27 61 62 77]
 [21 29 56 78 86]]
[[12  2 23  4 27]
 [40 17 60 14 29]
 [56 21 61 24 36]
 [77 62 74 56 44]
 [86 80 78 56 65]]
[214 193 186 241 270]
[271 182 296 154 201]
[4 3 3 5 2]


:

In [ ]:
a=np.random.randint(20,80,25,dtype=int)
b=np.random.randint(20,80,25,dtype=int)
stock=a.reshape(5,5)
demand=b.reshape(5,5)
print(stock)
print(demand)
remain=stock-demand;
print(remain)
l=np.where(remain<0,0,remain);
print(l)
# for total sortage of product
x=np.sum(np.where(remain<0,-remain,0))
print(x)
#product with zero stocks
x=np.sum(np.where(l==0,1,0),axis=0)
print(x)
print(np.sort(remain,axis=0))
print(np.sort(remain,axis=1))

[[27 67 39 58 27]
 [40 64 40 44 61]
 [71 56 79 75 25]
 [61 55 77 63 68]
 [78 55 47 53 40]]
[[74 37 54 50 77]
 [64 41 66 47 66]
 [33 37 37 45 69]
 [52 24 78 75 76]
 [47 73 69 58 24]]
[[-47  30 -15   8 -50]
 [-24  23 -26  -3  -5]
 [ 38  19  42  30 -44]
 [  9  31  -1 -12  -8]
 [ 31 -18 -22  -5  16]]
[[ 0 30  0  8  0]
 [ 0 23  0  0  0]
 [38 19 42 30  0]
 [ 9 31  0  0  0]
 [31  0  0  0 16]]
280
[2 1 4 3 4]
[[-47 -18 -26 -12 -50]
 [-24  19 -22  -5 -44]
 [  9  23 -15  -3  -8]
 [ 31  30  -1   8  -5]
 [ 38  31  42  30  16]]
[[-50 -47 -15   8  30]
 [-26 -24  -5  -3  23]
 [-44  19  30  38  42]
 [-12  -8  -1   9  31]
 [-22 -18  -5  16  31]]


In [ ]:
import pandas as pd
file1=pd.read_csv("student_data.csv",sep=",")#seperartor is by default comma
# df=pd.DataFrame()
print(file1)
print(". ")
print(file1.head())#give first n number of row by default it is 5
print(file1.head(8))

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   